gesdinet_jwt_refresh_token:
    refresh_token_class: App\Auth\Entity\RefreshToken
    ttl: '%env(int:JWT_REFRESH_TOKEN_TTL)%'
    ttl_update: true
    single_use: false

    # Read refresh token from cookie
    token_parameter_name: refresh_token
    cookie:
        enabled: true
        same_site: lax
        path: /
        domain: null
        http_only: true
        secure: false  # Set to true in production
        remove_token_from_body: true

    return_expiration: false
