lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(int:JWT_ACCESS_TOKEN_TTL)%'

    # Extract JWT from cookies instead of Authorization header
    token_extractors:
        cookie:
            enabled: true
            name: access_token
